version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=news_db
      - DB_MAX_OPEN_CONNS=50
      - DB_MAX_IDLE_CONNS=20
      - DB_CONN_MAX_LIFETIME=5
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_READ_TIMEOUT=15
      - level=-1
      - encoding=console
      - info_filename=logs/application.log
      - info_max_size=100
      - info_max_backups=30
      - info_max_age=90
      - info_compress=true
      - error_filename=logs/application_error.log
      - error_max_size=100
      - error_max_backups=30
      - error_max_age=90
      - error_compress=true
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=news_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  postgres_data: 